### PR TITLE
Loosen multi_json requirement

### PR DESCRIPTION
**Pull request by datapimp**
The tests pass.

### CODE REVIEW

**Comment by datapimp** [comment]
@tokengeek can you please merge this?

**Comment by plribeiro3000** [comment]
@datapimp Could you please not play with the version of the lib?

Its better to do the bump outside of any code related task. Once you do this i can merge it right away.

Thanks!

**Comment by datapimp** [comment]
@plribeiro3000 reverted the commit, gracias Paulo

**Comment by plribeiro3000** [comment]
Awesome. Thanks!

**Comment by datapimp** [comment]
will you be making a push to rubygems with a new version?

**Comment by plribeiro3000** [comment]
@datapimp I don't have access to cut a new release but @geemus or @tokengeek can help us here. =)

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
Released in 1.0.2

**Pull request merged**
